# Generated by Django 4.1.3 on 2022-11-26 15:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("thumbnail", models.ImageField(upload_to="course/thumbnail")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.FileField(
                        blank=True, null=True, upload_to="course/resource"
                    ),
                ),
                ("length", models.IntegerField()),
                ("prerequisite", models.CharField(max_length=50)),
                ("learning", models.CharField(max_length=50)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_description", models.CharField(max_length=500, null=True)),
                ("serial_number", models.IntegerField()),
                ("video_id", models.CharField(max_length=100)),
                ("resource", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "resource_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_preview", models.BooleanField(default=False)),
                (
                    "video_unique_id",
                    models.CharField(
                        blank=True, default=uuid.uuid4, max_length=100, unique=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "section_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.sectionvideo",
                    ),
                ),
            ],
        ),
    ]
