# Generated by Django 4.1.3 on 2022-12-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mark",
            name="student_user",
        ),
        migrations.AddField(
            model_name="mark",
            name="student_submitted_assessment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.submittedassessment",
            ),
            preserve_default=False,
        ),
    ]
