# Generated by Django 4.1 on 2022-12-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_mark_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedassessment",
            name="feedback",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="submittedassessment",
            name="obtained_mark",
            field=models.IntegerField(default=0),
        ),
    ]
