# Generated by Django 4.1.3 on 2022-12-23 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0005_enrollcourse"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnrollCourse",
            new_name="EnrolledCourse",
        ),
    ]
