# Generated by Django 4.1.3 on 2022-12-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_rename_enrollcourse_enrolledcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedassessment",
            name="student_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.enrolledcourse"
            ),
        ),
    ]
