# Generated by Django 4.1.3 on 2022-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_submittedassessment_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolledcourse",
            name="enrolled",
            field=models.BooleanField(default=True),
        ),
    ]
