# Generated by Django 4.1 on 2023-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_enrolledcourse_enrolled"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="top_course",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="resource_title",
            field=models.CharField(default="Assessment", max_length=100),
        ),
    ]
