# Generated by Django 4.1.3 on 2023-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(to="courses.category"),
        ),
    ]
